
##########################
#                        #
#        Example         #
#        Service         #
#                        #
#                        #
##########################
# petstore service
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aisu
  name: aisu
  namespace: default
spec:
  selector:
    matchLabels:
      app: aisu
  replicas: 1
  template:
    metadata:
      labels:
        app: aisu
    spec:
      containers:
      - image: soloio/aisu-example:latest
        name: aisu
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: aisu
  namespace: default
  labels:
    service: aisu
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: aisu
